openapi: 3.0.3
info:
  title: Exchange Currency API
  description: |-
    ** Exchange Currency API **
  version: 1.0.0
servers:
  - url: /exchangeCurrency/swagger-ui/index.html
tags:
  - name: exchange currency API
paths:
  /createAccount:
    post:
      summary: creates currency exchange account
      operationId: createAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccount'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountCreated'
        '400':
          description: Bad request body supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Request cannot be processed due to errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /exchange:
    post:
      summary: exchange one currency for another
      operationId: exchangeCurrency
      parameters:
        - name: accountNumber
          in: query
          description: account number
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExchangeCurrency'
      responses:
        '201':
          description: Successful operation
        '400':
          description: Bad request body supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Request cannot be processed due to errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /accountBalance:
    get:
      summary: get account balances
      operationId: getAccountBalance
      parameters:
        - name: accountNumber
          in: query
          description: account number
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountBalance'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    CreateAccount:
      type: object
      required:
        - firstName
        - lastName
        - initialBalance
      properties:
        firstName:
          type: string
        lastName:
          type: string
        initialBalance:
          $ref: '#/components/schemas/AccountBalance'
    AccountCreated:
      type: object
      properties:
        accountNumber:
          type: string
    AccountBalance:
      type: object
      required:
        - currencyCode
        - balance
      properties:
        currencyCode:
          $ref: '#/components/schemas/CurrencyCode'
        balance:
          type: number
          format: decimal
    ExchangeCurrency:
      type: object
      required:
        - sourceCurrencyCode
        - targetCurrencyCode
        - amountSourceCurrency
      properties:
        sourceCurrencyCode:
          $ref: '#/components/schemas/CurrencyCode'
        targetCurrencyCode:
          $ref: '#/components/schemas/CurrencyCode'
        amountSourceCurrency:
          type: number
          format: decimal
    CurrencyCode:
      type: string
      enum:
        - USD
        - PLN
    Error:
      type: object
      required:
        - errorMessage
      properties:
        errorMessage:
          type: string

