spring:
  datasource:
    url: jdbc:h2:mem:memdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/migration/db.changelog.master.xml
  flyway:
    enabled: false
  h2:
    console:
      enabled: true



