server:
  port: 8080
  servlet:
    context-path: /exchangeCurrency

spring:
  datasource:
    username: username
    password: password
    url: jdbc:postgresql://localhost:5432/exchange_currency_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/migration/db.changelog.master.xml
  flyway:
    enabled: false

integration:
  nbp:
    base-url: "http://api.nbp.pl/api/exchangerates/rates"
    timeout:
      connect: 1s
      response: 1s

logging:
  level:
    org:
      zalando:
        logbook:
          Logbook: TRACE